services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 99tech
      DB_NAME: 99tech_db
    depends_on:
      database:
        condition: service_healthy
    networks:
      - 99tech-network

  database:
    image: mysql:8.0
    container_name: 99tech_database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 99tech
      MYSQL_DATABASE: 99tech_db
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p99tech"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - 99tech-network

volumes:
  db_data:
networks:
  99tech-network:
